name: neo4j_http_client
description: A Dart/Flutter library for interacting with the Neo4j HTTP API.
version: 2023.1.0
repository: https://github.com/szktty/dart-neo4j-http-client

environment:
  sdk: '>=2.19.6 <3.0.0'

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  lints: ^2.0.1
  test: ^1.24.2
dependencies:
  freezed_annotation: ^2.2.0
  http: ^1.1.0
  json_annotation: ^4.8.0
  very_good_analysis: ^4.0.0+1
